### ISSUE TITLE
PullRequestOpenedEvent.pull_request is never

### ISSUE THREAD

**Issue by Shigma** [octokit/webhooks#409] opened 2021-03-21 15:15 UTC
**What happened?**

![image](https://user-images.githubusercontent.com/33423008/111910158-33e2d600-8a9b-11eb-9e84-670110bd8b03.png)

**What did you expect to happen?**

non-never

**What the problem might be**

**Comment by wolfy1339** [comment] 2021-03-21 15:17
This isn't a bug. If you look at the actual source code of the TS definitions, you'll see that it isn't `never`.

You will need to enable `strictNullChecks` in your `tsconfig.json`.

Duplicate of #395, #398

**Closed by wolfy1339** 2021-03-21 15:17 UTC
Labels: support, typescript
